### ISSUE TITLE
12월 6일까지 계발계획입니다.

### ISSUE THREAD

**Issue by halucinor** [halucinor/Your_Taste_My_Taste#103]
##Due date : 12.06(금)##

빠진부분이나 수정이 필요한 부분이나 추가할 부분 코멘트나 카톡 보내주세요!
작업할 수 있는부분 이름 쓰고 가져가서 작업해주세요!

**문서작업 일정**
	12.10 전시계획 회의
	12.13 최종 발표 ppt
	12.20 최종 보고서 

**기능 구현**
	
        1. 메뉴 재료 DB 작업 -> 백승주 @halucinor 

	2. 메뉴 추천 이후 음식점 추천 -> 백승주 유세정 @halucinor @ellen201621147 
		식당 리스트 검색 기능 -> 유세정 @ellen201621147 
		식당 정보 확인 기능

	3. 회원 가입/비밀번호 찾기 관련 이슈 -> 유은정 방진실 @lm040466 @progjs 
		아이디 중복이 발생했을 경우 예외 처리가 필요합니다.
		
	4. 회원 정보 수정 -> 백승주 @halucinor 
		싫어하는 음식페이지에 접속할 경우 기존 프로필을 조회하여 해당 리스트를 출력해주어야 합니다.
		알레르기 페이지도 위와 동일합니다.

	5. 주변 인기 메뉴 추천 -> X
		아주대 1km 이내 음식점 정보를 DB에 저장해야합니다.
		지도상에서 아주대 주변에서 인기 있는 메뉴를 찾을 수 있어야 합니다(좋아요 수를 기반으로)
		주변 인기 메뉴 추천 기능은 구체화가 더 필요할거 같습니다. 회의를 통해 해당 기능을 어떻게 서비스할지 상의해봐야할거 같습니다.
		
	6. 생일 관련 이슈 -> 방진실 @progjs
		생일 입력 시 시간까지 나오는 경우가 있습니다.
		회원 가입 시 시간을 입력하지 않으면 오류를 일으키는 경우가 있습니다.
		
	7. 회원가입 시 다른 버튼을 연속으로 누르면 둘다 누른 이미지가 나옴 -> 유세정 @ellen201621147

**Comment by lm040466** [comment]
3. 회원 가입 시 이메일 인증 기능이 필요합니다. -> 유효성 있는 사용자를 저장하기 위한 기능이지만 현재는 회원가입의 편리를 위하여 삭제합니다.
비밀 번호 찾기 시 사용자 계정의 이메일에 재설정된 비밀번호를 전송해야합니다. -> 완료

**Comment by progjs** [comment]
6번 완료.
3번 완료.

**Comment by progjs** [comment]
7번 @ellen201621147 완료.
