### ISSUE TITLE
디테일 수정사항입니다.

### ISSUE THREAD

**Issue by lm040466** [halucinor/Your_Taste_My_Taste#116]
##Due date : 12.13(금)##

빠진부분이나 수정이 필요한 부분이나 추가할 부분 코멘트나 카톡 보내주세요!
작업할 수 있는부분 이름 쓰고 가져가서 작업해주세요!

**수정사항**
	
- [x] 1. signup: 중복확인버튼 줄 맞추기 -> 방진실 @progjs 

- [x] 2. 회원가입 뒤로가기/중간취소 예외처리 -> 유은정 @lm040466 

- [ ] 3. 생일 입력범위(1900-오늘날짜) -> 방진실 @progjs 

- [x] 4. 채식주의 문구 두줄로(넘치지 않게) -> 방진실 @progjs 

~~- 5. 마이페이지-회원정보수정 비밀번호 입력 페이지(mypage/selectinfo)~~

- [ ] 6. 비밀번호/이메일 별도 수정 가능(mypage/infomodify)

- [x] 7. 이메일 수정 시 아이디/도메인 별도 요청(mypage/infomodify)

- [x] 8. 알레르기/개인적 식성 기존 목록 생성(mypage/allergymodify, mypage/hatemodify) -> 백승주 @halucinor 

- [x] 9. 회원이미지 변경(친구목록, 그룹메뉴추천) -> 방진실 @progjs 

- [x] 10. 메뉴설명에 'None ' 처리(menureco)

- [x] 11. '주변인기메뉴추천' 준비중 페이지 연결(12/13 금 까지 개발) -> 백승주 @halucinor 

- [x] 12. 아이디 중복확인

- [x] 13. 세번째기능 없애기

- [x] 14. 메뉴사진 클릭시 위치기반페이지로 이동

- [x] 15. 위치기반페이지로 넘어갈수있다고 코멘트 쓰기

**Comment by progjs** [comment]
5. 페이지 추가없이 이메일/비밀번호 수정시에만 비밀번호 입력하는 것으로 변경 어떨까요

**Comment by ellen201621147** [comment]
12. 친구와 함께 추천 받기 버튼 혼자서 개길어서 다시 짧게 고쳤슴다
