### ISSUE TITLE
기능 구현 목록

### ISSUE THREAD

**Issue by halucinor** [halucinor/Your_Taste_My_Taste#81]
1. 회원가입 이슈
 사용자 정보 확인 페이지
 중복 사용자에 대한 처리
 없는 메뉴, 재료 추가 시 백엔드 처리 방식

2. 로그인 못했을 때 매시지

3. 친구 기능
	친구목록 관리 페이지
		1. 친구 추가
		2. 친구 목록 갱신
		3. 친구 조회

4. 좋아요 버튼
	1. 프론트 엔드 좋아요 버튼 작동
	2. 백엔드 좋아요 업데이트
		
5. 마이페이지 정보 수정 기능
	*

6. 지도 API 적용한 주변 식당 검색 기능
	1. 프론트 엔드 지도 사용
	2. API 검색 후 백엔드에서 정보 업데이트
	3. Ajax로 음식점 정보 모양에 페이지에 전시

**Comment by progjs** [comment]
2번 3번 완료
