### ISSUE TITLE
11.25 ~ 11.26 진도 점검 결과

### ISSUE THREAD

**Issue by halucinor** [halucinor/Your_Taste_My_Taste#91]
### 19.11.25 ~ 19.11.26 진도 점검
	
빠진부분이나 수정이 필요한 부분이나 추가할 부분 코멘트나 카톡 보내주세요!
작업할 수 있는부분 이름 쓰고 가져가서 작업해주세요!

**문서작업**
1. 전시 포스터 -> O (교수님 피드백 후 수정 필요)
2. 소프트콘 보고서 -> 기획서, 설계서 활용해서 완성해야함

**기능 구현**
1. 친구 CRUD 페이지  -> O
2. 친구 찾아서 등록 후 같이 먹기 기능 -> 백승주 작업 중(80%)
3. 협업 필터링 알고리즘 적용 -> 백승주
4. 모바일 화면에 적합하게 UI 재설계 -> O
5. 좋아요 버튼 작동 및 history 페이지 생성 -> 진실
6. 메뉴 재료 DB 작업 -> X
7. 메뉴 추천 이후 음식점 추천

- 현재 위치 중심 지도 출력 -> O
- 식당 리스트 검색 기능
- 식당 정보 확인 기능

7. 회원가입 마지막 단계(프로필 생성 결과) 페이지 : 개인 식성 설정 페이지 이후 회원가입 된 프로필을 확인할 수 있는 페이지를 만들어야 합니다 -> X
8. 회원 가입/비밀번호 찾기 관련 이슈

- 아이디 중복이 발생했을 경우 예외 처리가 필요합니다. -> X
- 회원 가입 시 이메일 인증 기능이 필요합니다. -> X
- 비밀 번호 찾기 시 사용자 계정의 이메일에 재설정된 비밀번호를 전송해야합니다. -> X
- 아이디/비밀번호 찾기 기능이 구현되어야합니다. -> X

9. 회원 정보 수정

- 싫어하는 음식페이지에 접속할 경우 기존 프로필을 조회하여 해당 리스트를 출력해주어야 합니다. -> X
- 알레르기 페이지도 위와 동일합니다. -> X

10. 주변 인기 메뉴 추천 -> X

- 아주대 1km 이내 음식점 정보를 DB에 저장해야합니다.
- 지도상에서 아주대 주변에서 인기 있는 메뉴를 찾을 수 있어야 합니다(좋아요 수를 기반으로)
- 주변 인기 메뉴 추천 기능은 구체화가 더 필요할거 같습니다. 회의를 통해 해당 기능을 어떻게 서비스할지 상의해봐야할거 같습니다.

@progjs @lm040466 @ellen201621147 고생했습니다

**Comment by halucinor** [comment]
6. 메뉴 재료 DB 작업 -> 백승주

**Comment by halucinor** [comment]
.7. 메뉴 추천 이후 음식점 추천 -> 백승주

**Comment by progjs** [comment]
5. 맨 처음 좋아요 상태설정만 하면 됩니다.

**Comment by lm040466** [comment]
8. 회원 가입/비밀번호 찾기 관련 이슈 -> 유은정

**Comment by halucinor** [comment]
9. 회원 정보 수정 페이지

**Comment by ellen201621147** [comment]
7. 식당 리스트 검색 기능 -> 유세정
