### ISSUE TITLE
11.29 기능 개발 계획

### ISSUE THREAD

**Issue by halucinor** [halucinor/Your_Taste_My_Taste#94]
##**Due date : 12.04**

#교수님 미팅시간에 개발 현황을 보여드릴 겁니다.

빠진부분이나 수정이 필요한 부분이나 추가할 부분 코멘트나 카톡 보내주세요!
작업할 수 있는부분 이름 쓰고 가져가서 작업해주세요!

	**문서작업**
	캡디 판넬 제작 : 12.3 -> 백승주
	멘토링 내용 : 사진, 멘토링 받은 내용을 정리해서 교수님께 메일 보내야 합니다.

	**기능 구현**
	1. 친구 찾아서 등록 후 같이 먹기 기능 -> 백승주 작업 중 11.30 완성 @halucinor 

	2. 협업 필터링 알고리즘 적용 -> 백승주 12.1 @halucinor 

	3. 좋아요 버튼 작동 및 history 페이지 생성 -> 진실 @progjs 

	4. 메뉴 재료 DB 작업 -> 백승주 12.2 @halucinor 

	5. 메뉴 추천 이후 음식점 추천 -> 백승주 유세정 @halucinor @ellen201621147 
		식당 리스트 검색 기능 -> 유세정 @ellen201621147 
		식당 정보 확인 기능

	6. 회원가입 마지막 단계 -> X
		프로필 생성 결과 페이지 : 개인 식성 설정 페이지 이후 회원가입 된 프로필을 확인할 수 있는 페이지를 만들어야 합니다

	7. 회원 가입/비밀번호 찾기 관련 이슈 -> 유은정 @lm040466 
		아이디 중복이 발생했을 경우 예외 처리가 필요합니다.
		회원 가입 시 이메일 인증 기능이 필요합니다.
		비밀 번호 찾기 시 사용자 계정의 이메일에 재설정된 비밀번호를 전송해야합니다.
		아이디/비밀번호 찾기 기능이 구현되어야합니다.
		
	8. 회원 정보 수정 -> 백승주 @halucinor 
		싫어하는 음식페이지에 접속할 경우 기존 프로필을 조회하여 해당 리스트를 출력해주어야 합니다.
		알레르기 페이지도 위와 동일합니다.

	9. 주변 인기 메뉴 추천 -> X
		아주대 1km 이내 음식점 정보를 DB에 저장해야합니다.
		지도상에서 아주대 주변에서 인기 있는 메뉴를 찾을 수 있어야 합니다(좋아요 수를 기반으로)
		주변 인기 메뉴 추천 기능은 구체화가 더 필요할거 같습니다. 회의를 통해 해당 기능을 어떻게 서비스할지 상의해봐야할거 같습니다.

**Comment by progjs** [comment]
3.history 11.30 완성 (menureco에서의 like status만 수정하면 됩니다. history는 기본적으로 좋아요를 누른 메뉴만 보여주기 때문에 default가 like라 status가 필요없습니다.)
6. 방진실 @progjs

**Comment by ellen201621147** [comment]
5. 일단 메뉴 누르면 바로 카카오 맵 사이트로 들어가도록 해놨습니다.

**Comment by progjs** [comment]
회원가입 페이지번호 추가했습니다. pull request는 나중에 하겠습니다.

**Comment by progjs** [comment]
7번에 3번 완료/ 2번 하는중 @lm040466

**Comment by progjs** [comment]
6번 완료. pull request는 나중에 하겠습니다.

**Comment by progjs** [comment]
7. 아이디 중복시, 예외처리
생일 현재보다 늦은 날짜 입력시 오류뜹니다.
생일 저장 시, 현시각까지 저장됩니다.
@halucinor  @lm040466
